const products = [
  {
    id: 1,
    name: 'Product 1',
    image: '/images/Image1.png',
    descriprion: 'This is a discription 1 for Product number 1',
    brand: 'Brand 1',
    category: 'Category 1',
    price: 100.99,
    rating: 3.5,
    countInStock: 10,
    numReviews: 5,
  },
  {
    id: 2,
    name: 'Product 2',
    image: '/images/Image2.png',
    descriprion: 'This is a discription 2 for Product number 2',
    brand: 'Brand 2',
    category: 'Category 2',
    price: 100.99,
    rating: 4.5,
    countInStock: 10,
    numReviews: 5,
  },
  {
    id: 3,
    name: 'Product 3',
    image: '/images/Image3.jpg',
    descriprion: 'This is a discription 3 for Product number 3',
    brand: 'Brand 3',
    category: 'Category 3',
    price: 100.99,
    rating: 2.5,
    countInStock: 10,
    numReviews: 5,
  },
  {
    id: 4,
    name: 'Product 4',
    image: '/images/Image4.jpg',
    descriprion: 'This is a discription 4 for Product number 4',
    brand: 'Brand 4',
    category: 'Category 4',
    price: 400.99,
    rating: 3,
    countInStock: 40,
    numReviews: 5,
  },
  {
    id: 5,
    name: 'Product 5',
    image: '/images/Image5.jpg',
    descriprion: 'This is a discription 5 for Product number 5',
    brand: 'Brand 5',
    category: 'Category 5',
    price: 500.99,
    rating: 1.5,
    countInStock: 10,
    numReviews: 5,
  },
  {
    id: 6,
    name: 'Product 6',
    image: '/images/Image6.jpg',
    descriprion: 'This is a discription 6 for Product number 6',
    brand: 'Brand 6',
    category: 'Category 6',
    price: 600.99,
    rating: 5,
    countInStock: 60,
    numReviews: 5,
  },
  {
    id: 7,
    name: 'Product 7',
    image: '/images/Image7.jpg',
    descriprion: 'This is a discription 7 for Product number 7',
    brand: 'Brand 7',
    category: 'Category 7',
    price: 700.99,
    countInStock: 70,
    rating: 1.5,
    numReviews: 5,
  },
  {
    id: 8,
    name: 'Product 8',
    image: '/images/Image8.jpg',
    descriprion: 'This is a discription 8 for Product number 8',
    brand: 'Brand 8',
    category: 'Category 8',
    price: 100.99,
    rating: 3.5,
    countInStock: 10,
    numReviews: 5,
  },
  {
    id: 9,
    name: 'Product 9',
    image: '/images/Image9.jpg',
    descriprion: 'This is a discription 9 for Product number 9',
    brand: 'Brand 9',
    category: 'Category 9',
    price: 900.99,
    rating: 3.5,
    countInStock: 90,
    numReviews: 5,
  },
  {
    id: 10,
    name: 'Product 10',
    image: '/images/Image10.jpg',
    descriprion: 'This is a discription 10 for Product number 10',
    brand: 'Brand 10',
    category: 'Category 10',
    price: 100.99,
    rating: 3.5,

    countInStock: 10,
    numReviews: 5,
  },
  {
    id: 11,
    name: 'Product 11',
    image: '/images/Image11.jpg',
    descriprion: 'This is a discription 11 for Product number 11',
    brand: 'Brand 11',
    category: 'Category 11',
    price: 1100.99,
    rating: 3.5,

    countInStock: 110,
    numReviews: 5,
  },
  {
    id: 12,
    name: 'Product 12',
    image: '/images/Image12.jpg',
    descriprion: 'This is a discription 12 for Product number 12',
    brand: 'Brand 12',
    category: 'Category 12',
    rating: 3.5,

    price: 1200.99,
    countInStock: 120,
    numReviews: 5,
  },
  {
    id: 13,
    name: 'Product 13',
    image: '/images/Image13.jpg',
    descriprion: 'This is a discription 13 for Product number 13',
    brand: 'Brand 13',
    category: 'Category 13',
    price: 1300.99,
    rating: 3.5,

    countInStock: 10,
    numReviews: 5,
  },
  {
    id: 14,
    name: 'Product 14',
    image: '/images/Image14.jpg',
    descriprion: 'This is a discription 14 for Product number 14',
    brand: 'Brand 14',
    category: 'Category 14',
    price: 100.99,
    countInStock: 10,
    rating: 3.5,

    numReviews: 5,
  },
  {
    id: 15,
    name: 'Product 15',
    image: '/images/Image15.jpg',
    descriprion: 'This is a discription 15 for Product number 15',
    brand: 'Brand 15',
    category: 'Category 15',
    price: 100.99,
    countInStock: 10,
    rating: 3.5,

    numReviews: 5,
  },
  {
    id: 16,
    name: 'Product 16',
    image: '/images/Image16.jpg',
    descriprion: 'This is a discription 16 for Product number 16',
    brand: 'Brand 16',
    category: 'Category 16',
    price: 100.99,
    countInStock: 10,
    rating: 3.5,

    numReviews: 5,
  },
  {
    id: 17,
    name: 'Product 17',
    image: '/images/Image17.jpg',
    descriprion: 'This is a discription 17 for Product number 17',
    brand: 'Brand 17',
    category: 'Category 17',
    price: 1800.99,
    countInStock: 10,
    rating: 3.5,

    numReviews: 5,
  },
  {
    id: 18,
    name: 'Product 18',
    image: '/images/Image18.jpg',
    descriprion: 'This is a discription 18 for Product number 18',
    brand: 'Brand 18',
    category: 'Category 18',
    price: 100.99,
    countInStock: 10,
    rating: 3.5,

    numReviews: 5,
  },
  {
    id: 19,
    name: 'Product 19',
    image: '/images/Image19.jpg',
    descriprion: 'This is a discription 19 for Product number 19',
    brand: 'Brand 19',
    category: 'Category 19',
    price: 100.99,
    rating: 3.5,

    countInStock: 10,
    numReviews: 5,
  },
  {
    id: 20,
    name: 'Product 20',
    image: '/images/Image20.jpg',
    descriprion: 'This is a discription 20 for Product number 20',
    brand: 'Brand 20',
    category: 'Category 20',
    price: 100.99,
    countInStock: 10,
    rating: 3.5,

    numReviews: 5,
  },
]
export default products
